// <auto-generated />
namespace SlotMachine.Models
{
  /// <summary>
  /// ImageEntity class
  /// </summary>
  public class ImageEntity
  {
    /// <summary>
    /// LeftSource property
    /// </summary>
    public string LeftSource { get; set; }

    /// <summary>
    /// LeftCoefficent property
    /// </summary>
    public double LeftCoefficent { get; set; } = 0.0;

    /// <summary>
    /// MiddleSource property
    /// </summary>
    public string MiddleSource { get; set; }

    /// <summary>
    /// MiddleCoefficent property
    /// </summary>
    public double MiddleCoefficent { get; set; } = 0.0;

    /// <summary>
    /// RightSource property
    /// </summary>
    public string RightSource { get; set; }

    /// <summary>
    /// RightCoefficent property
    /// </summary>
    public double RightCoefficent { get; set; } = 0.0;
  }
}
