// <auto-generated />
namespace SlotMachine.Models
{
  using SlotMachine.Common;

  /// <summary>
  /// SlotMachineModel class
  /// </summary>
  public class SlotMachineModel
  {
    /// <summary>
    /// SlotMachineModel constructor
    /// </summary>
    public SlotMachineModel()
    {
      Sources = new ImageEntity[ConstantsClass.rowsNumber];
    }

    /// <summary>
    /// IsGameRunning property
    /// </summary>
    public bool IsGameRunning { get; set; } = false;

    /// <summary>
    /// IsGameOver property
    /// </summary>
    public bool IsGameOver { get; set; } = false;
    /// <summary>
    /// Balance property
    /// </summary>
    public double Balance { get; set; } = 0.0;

    /// <summary>
    /// Bet property
    /// </summary>
    public double Bet { get; set; } = 0.0;

    /// <summary>
    /// Won property
    /// </summary>
    public double Won { get; set; } = 0.0;

    /// <summary>
    /// Sources property
    /// </summary>
    public ImageEntity[] Sources { get; set; }
  }
}
