// <auto-generated />
namespace SlotMachine.Common
{
  using System.Collections.Generic;

  /// <summary>
  /// Constant class
  /// </summary>
  public static class ConstantsClass
  {
    /// <summary>
    /// SymbolNumber field
    /// </summary>
    public static int rowsNumber = 4;

    /// <summary>
    /// SymbolsSorces property
    /// </summary>
    public static List<string> SymbolImageSources { get; } = new List<string>()
      {
        "/images/apple.png", "/images/banana.png", "/images/wildcard.png", "/images/pineapple.png"
      };

    /// <summary>
    /// SymbolWeights property
    /// </summary>
    public static List<double> SymbolWeights { get; } = new List<double>()
    {
      0, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.8, 0.8, 0.8
    };

    /// <summary>
    /// SymbolCoefficents property
    /// </summary>
    public static List<double> SymbolCoefficents { get; } = new List<double>()
    {
      0.4, 0.6, 0, 0.8
    };
  }
}
