// <auto-generated />
namespace SlotMachine.BisinessLayer
{
  using global::SlotMachine.Models;

  /// <summary>
  /// ISlotMachine interface
  /// </summary>
  public interface ISlotMachine
  {
    /// <summary>
    /// GetNewBettingCoefficents contract
    /// </summary>
    /// <returns></returns>
    SlotMachineModel GetNewBettingCoefficents();

    /// <summary>
    /// GetRandomNumberInRange contract
    /// </summary>
    /// <returns></returns>
    int GetRandomNumberInRange();

    /// <summary>
    /// CalculateProfit contract
    /// </summary>
    /// <param name="bet"></param>
    void CalculateProfit(ref SlotMachineModel bet);

    /// <summary>
    /// SumCoefficents contract
    /// </summary>
    /// <param name="coefficents"></param>
    /// <returns></returns>
    double SumCoefficents(ImageEntity coefficents);

    /// <summary>
    /// AllEqual contract
    /// </summary>
    /// <param name="values"></param>
    /// <returns></returns>
    bool AllEqual(params double[] values);
  }
}
